Blockly.Msg.WEBDUINO_THERMISTOR = "熱敏電阻";
Blockly.Msg.WEBDUINO_THERMISTOR_DETECTED = "開始偵測";
Blockly.Msg.WEBDUINO_THERMISTOR_DO = "執行";
Blockly.Msg.WEBDUINO_THERMISTOR_PIN = "熱敏腳位";
Blockly.Msg.WEBDUINO_THERMISTOR_VAL = "目前溫度";
Blockly.Msg.WEBDUINO_THERMISTOR_STOP = "停止偵測";
